{
  "formatVersion": "1.1",
  "component": {
    "group": "io.webpkit",
    "module": "player",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "player-1.0.5.aar",
          "url": "player-1.0.5.aar",
          "size": 523365,
          "sha512": "d09e10f5f9fb3ef11960920127c4baef51613854fbb72923e1fb36559f9afeea848efb5787e32acaa1298ca81af8b58c4d75ea8bae282dd5545a319b8cb301e5",
          "sha256": "c6e87e29a1b6817fd4e8dc14ade36103ee5d0f5946c83a91217e40c5be772d65",
          "sha1": "78eb012f1216a583d626a5d2a9f78baa91561b7a",
          "md5": "393dc3d05da56153aef8a8a9439ce1bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "player-1.0.5.aar",
          "url": "player-1.0.5.aar",
          "size": 523365,
          "sha512": "d09e10f5f9fb3ef11960920127c4baef51613854fbb72923e1fb36559f9afeea848efb5787e32acaa1298ca81af8b58c4d75ea8bae282dd5545a319b8cb301e5",
          "sha256": "c6e87e29a1b6817fd4e8dc14ade36103ee5d0f5946c83a91217e40c5be772d65",
          "sha1": "78eb012f1216a583d626a5d2a9f78baa91561b7a",
          "md5": "393dc3d05da56153aef8a8a9439ce1bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "player-1.0.5-sources.jar",
          "url": "player-1.0.5-sources.jar",
          "size": 49447,
          "sha512": "018541aa40de745f7d2f329e1ec850fa943ad2e809e1cdaa1ee667bde259dfb5fb1d15a648648cde83d35e5f8ec5135df86abf2bb91777963c62dfe62b663c5d",
          "sha256": "e853f6efd961d2441957056a68f634c94fc1838be44a09b39284dc7703194dd2",
          "sha1": "679fc2d0050aea59ed4bd3b56945f2902502edcb",
          "md5": "36c4747da4ecd045f5bb636d3c878bec"
        }
      ]
    }
  ]
}
